[package]
name = "choochoo"
version = "0.1.0"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2018"

[features]
default = []
heap = ["linked_list_allocator"]

[dependencies]
r0 = "0.2"

choochoos-sys = { path = "./choochoos-sys" }

linked_list_allocator = { version =  "0.6", default-features = false, optional = true }

[workspace]
members = ["choochoos-sys"]
