[workspace]
members = [
    "choochoos-abi",
    "choochoos-api",
    "choochoos-kernel",
    "ts7200",

    "userspace/",
    "userspace/distros/k1",
    "userspace/distros/k2",
]

[profile.release]
panic = "abort"
lto = true
codegen-units = 1

[profile.dev]
panic = "abort"
debug = true
