[package]
name = "choochoo-rs"
version = "0.1.0"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2018"

[dependencies]
r0 = "0.2"

linked_list_allocator = { version =  "0.6", default-features = false }

embcrusted = { git = "https://github.com/daniel5151/embcrusted.git" }
