[package]
name = "choochoo"
version = "0.1.0"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2018"

[features]
default = []
heap = ["linked_list_allocator"]

k1 = ["userspace/k1"]
k2 = ["userspace/k2"]

[dependencies]
choochoos-sys = { path = "./choochoos-sys" }
generic-containers = { path = "./generic-containers" }
ts7200 = { path = "./ts7200" }

userspace = { path = "./userspace" }

linked_list_allocator = { version =  "0.8", default-features = false, optional = true }

[workspace]
members = [
    "choochoos-sys",
    "generic-containers",
    "ts7200",
    "userspace"
]

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
