[package]
name = "choochoo"
version = "0.1.0"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2018"

[features]
default = []
heap = ["linked_list_allocator"]

[dependencies]
r0 = "0.2"
linked_list_allocator = { version =  "0.6", default-features = false, optional = true }

choochoos-sys = { path = "./choochoos-sys" }
ts7200 = { path = "./ts7200" }

k1 = { path = "./k1", optional = true }

[workspace]
members = ["choochoos-sys", "ts7200", "k1"]
