[workspace]
members = [
    "choochoos-abi",
    "choochoos-api",
    "choochoos-kernel",
    "choochoos-user",
    "ts7200",
]

[profile.release]
panic = "abort"
lto = true
codegen-units = 1

[profile.dev]
panic = "abort"
debug = true
