[package]
name = "k1"
version = "0.1.0"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2018"

[dependencies]
choochoos-sys = { path = "../choochoos-sys" }
ts7200 = { path = "../ts7200" }
