[package]
name = "choochoos-kernel"
version = "0.1.0"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2018"

[features]
default = []
heap = ["linked_list_allocator"]
kdebug = []
legacy-implicit-exit = []

[dependencies]
choochoos-abi = { path = "../choochoos-abi" }
ts7200 = { path = "../ts7200" }

# armv4t doesn't support atomic operations, so the "cas" feature must be disabled
heapless = { version = "0.5", default-features = false }
owo-colors = "1.1"

linked_list_allocator = { version =  "0.8", default-features = false, optional = true }
