[package]
name = "choochoos-kernel"
version = "0.1.0"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2018"

[features]
default = []
heap = ["linked_list_allocator"]

k1 = ["choochoos-user/k1"]
k2 = ["choochoos-user/k2"]

[dependencies]
choochoos-sys = { path = "../choochoos-sys" }
generic-containers = { path = "../generic-containers" }
ts7200 = { path = "../ts7200" }

choochoos-user = { path = "../choochoos-user" }

linked_list_allocator = { version =  "0.8", default-features = false, optional = true }
